### ISSUE TITLE
The condition is wrong.

### ISSUE THREAD

**Issue by nerkaid** [kerthegreat/scuffed-rickroll-checker-in-python#1]
The condition is wrong, so any text input will be detected as rickroll.

Set the condition like:

`if ((rick == "https://www.youtube.com/watch?v=dQw4w9WgXcQ") or (rick == "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley")):`

or like:

`if rick in ["https://www.youtube.com/watch?v=dQw4w9WgXcQ", "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"]:`

Best regards!

**Comment by kerthegreat** [comment]
i see. thank you for correcting!
